In [1]:
a, b = 0, 1
while b < 2000000:
    print(b, end=' ')
    a, b = b, a+b

1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765 10946 17711 28657 46368 75025 121393 196418 317811 514229 832040 1346269 

In [2]:
a, b = 0, 1
while b < 20000000:
    print(b, end=' ')
    a, b = b, a+b


1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765 10946 17711 28657 46368 75025 121393 196418 317811 514229 832040 1346269 2178309 3524578 5702887 9227465 14930352 

In [3]:
2+2


4

In [4]:
import numpy as np

array = np.array(range(10))


In [5]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
array1 = np.array(range(100))

In [7]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
array1 * 2

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [9]:
import numpy as np
random_numbers = np.random.rand(10)
print(random_numbers)

[0.05798996 0.95597341 0.02848788 0.1122025  0.21015525 0.4075959
 0.94285421 0.48903284 0.6910078  0.7191619 ]


In [10]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [11]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [12]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [13]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [14]:
data1 = [6, 7.5, 8, 0, 1]

In [15]:
arr1 = np.array(data1)

In [16]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [17]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [18]:
arr2 = np.array(data2)

In [19]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
arr2.shape

(2, 4)

In [21]:
arr1.dtype

dtype('float64')

In [22]:
arr2.dtype

dtype('int64')

In [23]:
arr3 = np.arange(10)

In [24]:
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr2.dtype

dtype('int64')

In [26]:
floatarr2 = arr2.astype(np.float64)

In [27]:
floatarr2.dtype

dtype('float64')

In [28]:
floatarr2

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [29]:
arr = np.arange(10)

In [30]:
arr_slc = arr[5:8]

In [31]:
arr_slc

array([5, 6, 7])

In [32]:
arr_slc[0:2] = 12

In [33]:
arr_slc

array([12, 12,  7])

In [34]:
arr_slc[0:] = 12

In [35]:
arr_slc

array([12, 12, 12])

In [36]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [37]:
arr_slc[1] = 12345

In [38]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [39]:
arr_slc[:] = 64

In [40]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [41]:
import numpy as np

In [42]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [43]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [44]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr2d[2]

array([7, 8, 9])

In [46]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [48]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [49]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [50]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4 ]])

In [51]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [52]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [53]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [54]:
import numpy as np

In [55]:
a, b = 0, 1
while b < 2000000:
    print(b, end=' ')
    a, b = b, a+b

1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765 10946 17711 28657 46368 75025 121393 196418 317811 514229 832040 1346269 

In [56]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [57]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [58]:
a, b = 1346269, 2178309
while b < 20000000:
    print(b, end=' ')
    a, b = b, a+b

2178309 3524578 5702887 9227465 14930352 

In [59]:
new_random_number = np.random.rand()
print(new_random_number)

0.689423148928511


In [60]:
import pandas as pd

# Read the Excel file
df_excel = pd.read_excel('BDPT.xlsx')

# Display the dataframe
print(df_excel)

                      APELLIDO Y NOMBRE  \
0                ACOSTA, HUGO SABASTIAN   
1                     GIACHELLO, DAMIAN   
2                     FERNANDEZ, ALVARO   
3               GUZMÁN, RICARDO MARCELO   
4               GRESS, JONATHAN ALBERTO   
...                                 ...   
35350              REARTE, LUIS RODRIGO   
35351              RAUTA, FABIAN HECTOR   
35352               PARDO, LUIS ALBERTO   
35353            GONZALEZ, JUAN EMANUEL   
35354  GALARZA, CRISTIAN RAMIRO JOAQUIN   

                                    Columna2       FUNCIÓN Columna1  \
0                ACOSTA, HUGO SABASTIAN45443   TECNICO HyS      NaN   
1                     GIACHELLO, DAMIAN45443  JEFE DE OBRA      NaN   
2                     FERNANDEZ, ALVARO45443     INGENIERO      NaN   
3               GUZMÁN, RICARDO MARCELO45443       OFICIAL      NaN   
4               GRESS, JONATHAN ALBERTO45443      OFICINAL      NaN   
...                                      ...           ..

In [61]:
df_excel.head()

APELLIDO Y NOMBRE                      Columna2       FUNCIÓN  \
0   ACOSTA, HUGO SABASTIAN   ACOSTA, HUGO SABASTIAN45443   TECNICO HyS   
1        GIACHELLO, DAMIAN        GIACHELLO, DAMIAN45443  JEFE DE OBRA   
2        FERNANDEZ, ALVARO        FERNANDEZ, ALVARO45443     INGENIERO   
3  GUZMÁN, RICARDO MARCELO  GUZMÁN, RICARDO MARCELO45443       OFICIAL   
4  GRESS, JONATHAN ALBERTO  GRESS, JONATHAN ALBERTO45443      OFICINAL   

  Columna1             SECTOR    HR      FECHA  Unnamed: 7  Unnamed: 8  \
0      NaN                NaN   5.0 2024-05-31         NaN         NaN   
1      NaN                NaN   4.0 2024-05-31         NaN         NaN   
2      NaN  MED. RESISTIVIDAD  10.0 2024-05-31         NaN         NaN   
3      NaN   DETECCIÓN INTERF  10.0 2024-05-31         NaN         NaN   
4      NaN  LIMPIEZA  TERRENO  10.0 2024-05-31         NaN         NaN   

   Unnamed: 9  Unnamed: 10  Unnamed: 11 Unnamed: 12  
0         NaN          NaN          NaN         NaN  
1         NaN          NaN          NaN         NaN  
2         NaN          NaN          NaN         NaN  
3         NaN          NaN          NaN         NaN  
4         NaN          NaN          NaN         NaN

In [62]:
df_excel.tail()

APELLIDO Y NOMBRE  \
35350              REARTE, LUIS RODRIGO   
35351              RAUTA, FABIAN HECTOR   
35352               PARDO, LUIS ALBERTO   
35353            GONZALEZ, JUAN EMANUEL   
35354  GALARZA, CRISTIAN RAMIRO JOAQUIN   

                                    Columna2 FUNCIÓN Columna1 SECTOR    HR  \
35350              REARTE, LUIS RODRIGO45626     NaN      NaN    NaN  10.0   
35351              RAUTA, FABIAN HECTOR45626     NaN      NaN    NaN  10.0   
35352               PARDO, LUIS ALBERTO45626     NaN      NaN    NaN  10.0   
35353            GONZALEZ, JUAN EMANUEL45626     NaN      NaN    NaN   NaN   
35354  GALARZA, CRISTIAN RAMIRO JOAQUIN45626     NaN      NaN    NaN  10.0   

           FECHA  Unnamed: 7  Unnamed: 8  Unnamed: 9  Unnamed: 10  \
35350 2024-11-30         NaN         NaN         NaN          NaN   
35351 2024-11-30         NaN         NaN         NaN          NaN   
35352 2024-11-30         NaN         NaN         NaN          NaN   
35353 2024-11-30         NaN         NaN         NaN          NaN   
35354 2024-11-30         NaN         NaN         NaN          NaN   

       Unnamed: 11 Unnamed: 12  
35350          NaN         NaN  
35351          NaN         NaN  
35352          NaN         NaN  
35353          NaN         NaN  
35354          NaN         NaN

In [63]:
df_excel_cleaned = df_excel.dropna(how='all', axis=1)
df_excel_cleaned = df_excel_cleaned.dropna(how='all', axis=0)
print(df_excel_cleaned)

                      APELLIDO Y NOMBRE  \
0                ACOSTA, HUGO SABASTIAN   
1                     GIACHELLO, DAMIAN   
2                     FERNANDEZ, ALVARO   
3               GUZMÁN, RICARDO MARCELO   
4               GRESS, JONATHAN ALBERTO   
...                                 ...   
35350              REARTE, LUIS RODRIGO   
35351              RAUTA, FABIAN HECTOR   
35352               PARDO, LUIS ALBERTO   
35353            GONZALEZ, JUAN EMANUEL   
35354  GALARZA, CRISTIAN RAMIRO JOAQUIN   

                                    Columna2       FUNCIÓN Columna1  \
0                ACOSTA, HUGO SABASTIAN45443   TECNICO HyS      NaN   
1                     GIACHELLO, DAMIAN45443  JEFE DE OBRA      NaN   
2                     FERNANDEZ, ALVARO45443     INGENIERO      NaN   
3               GUZMÁN, RICARDO MARCELO45443       OFICIAL      NaN   
4               GRESS, JONATHAN ALBERTO45443      OFICINAL      NaN   
...                                      ...           ..

In [64]:
df_excel_cleaned.head()

APELLIDO Y NOMBRE                      Columna2       FUNCIÓN  \
0   ACOSTA, HUGO SABASTIAN   ACOSTA, HUGO SABASTIAN45443   TECNICO HyS   
1        GIACHELLO, DAMIAN        GIACHELLO, DAMIAN45443  JEFE DE OBRA   
2        FERNANDEZ, ALVARO        FERNANDEZ, ALVARO45443     INGENIERO   
3  GUZMÁN, RICARDO MARCELO  GUZMÁN, RICARDO MARCELO45443       OFICIAL   
4  GRESS, JONATHAN ALBERTO  GRESS, JONATHAN ALBERTO45443      OFICINAL   

  Columna1             SECTOR    HR      FECHA Unnamed: 12  
0      NaN                NaN   5.0 2024-05-31         NaN  
1      NaN                NaN   4.0 2024-05-31         NaN  
2      NaN  MED. RESISTIVIDAD  10.0 2024-05-31         NaN  
3      NaN   DETECCIÓN INTERF  10.0 2024-05-31         NaN  
4      NaN  LIMPIEZA  TERRENO  10.0 2024-05-31         NaN

In [65]:
df_excel_cleaned = df_excel_cleaned.drop(columns=["Columna1", "Columna2", "Unnamed: 12"])
print(df_excel_cleaned)

                      APELLIDO Y NOMBRE       FUNCIÓN             SECTOR  \
0                ACOSTA, HUGO SABASTIAN   TECNICO HyS                NaN   
1                     GIACHELLO, DAMIAN  JEFE DE OBRA                NaN   
2                     FERNANDEZ, ALVARO     INGENIERO  MED. RESISTIVIDAD   
3               GUZMÁN, RICARDO MARCELO       OFICIAL   DETECCIÓN INTERF   
4               GRESS, JONATHAN ALBERTO      OFICINAL  LIMPIEZA  TERRENO   
...                                 ...           ...                ...   
35350              REARTE, LUIS RODRIGO           NaN                NaN   
35351              RAUTA, FABIAN HECTOR           NaN                NaN   
35352               PARDO, LUIS ALBERTO           NaN                NaN   
35353            GONZALEZ, JUAN EMANUEL           NaN                NaN   
35354  GALARZA, CRISTIAN RAMIRO JOAQUIN           NaN                NaN   

         HR      FECHA  
0       5.0 2024-05-31  
1       4.0 2024-05-31  
2      10.0 

In [66]:
summary = df_excel_cleaned.groupby("APELLIDO Y NOMBRE").size()
print(summary)

APELLIDO Y NOMBRE
ABURTO, BARBARA               104
ACENCIO, NELSON EMANUEL        56
ACOSTA, DIEGO MAXIMILIANO     127
ACOSTA, HUGO SABASTIAN        168
ADAME, JOSÉ FORTUNATO         151
                             ... 
ZALAZAR, WILLIAN ALEJANDRO    115
ZAPATA, ROBERTO DARIO          66
ZEBALLOS, LEANDRO EMANUEL      78
ZURITA, JORGE GABRIEL          46
ZUÑIGA , DAVID MOISES          92
Length: 415, dtype: int64


In [67]:
summary.shape

(415,)

In [68]:
summary.shape

(415,)

In [69]:
hr_summary = df_excel_cleaned.groupby("APELLIDO Y NOMBRE")["HR"].sum()
print(hr_summary)

APELLIDO Y NOMBRE
ABURTO, BARBARA                540.0
ACENCIO, NELSON EMANUEL        324.0
ACOSTA, DIEGO MAXIMILIANO      854.0
ACOSTA, HUGO SABASTIAN        1238.0
ADAME, JOSÉ FORTUNATO         1080.0
                               ...  
ZALAZAR, WILLIAN ALEJANDRO     604.0
ZAPATA, ROBERTO DARIO          281.0
ZEBALLOS, LEANDRO EMANUEL      254.0
ZURITA, JORGE GABRIEL            0.0
ZUÑIGA , DAVID MOISES          540.0
Name: HR, Length: 415, dtype: float64


In [70]:
hr_summary.shape

(415,)

In [71]:
hr_summary.to_excel('hr_summary.xlsx', sheet_name='HR Summary')

In [72]:
import sqlite3

# Connect to the database (or create it if it doesn't exist)
conn = sqlite3.connect('new_database.db')

# Create a cursor object
cursor = conn.cursor()

# Create a new table
cursor.execute('''
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    age INTEGER,
    email TEXT
)
''')

# Commit the changes and close the connection
conn.commit()
conn.close()

In [73]:
# Connect to the existing database
conn = sqlite3.connect('new_database.db')

# Create a cursor object
cursor = conn.cursor()

# Verify the connection by fetching all tables
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()

# Print the tables in the database
print("Tables in the database:", tables)

Tables in the database: [('users',)]


In [74]:
# Connect to the existing database
conn = sqlite3.connect('new_database.db')

# Create a cursor object
cursor = conn.cursor()

# Fetch all records from the registers table
cursor.execute('SELECT * FROM users')
registers = cursor.fetchall()

# Print the fetched records
for register in registers:
    print(register)

# Close the connection
conn.close()

(2, 'Alice', 28, 'alice@example.com')
(3, 'Bob', 34, 'bob@example.com')
(4, 'Charlie', 22, 'charlie@example.com')
(5, 'Alice', 28, 'alice@example.com')
(6, 'Bob', 34, 'bob@example.com')
(7, 'Charlie', 22, 'charlie@example.com')


In [75]:
# Connect to the existing database
conn = sqlite3.connect('new_database.db')

# Create a cursor object
cursor = conn.cursor()

# Fetch the table fields
cursor.execute('PRAGMA table_info(users)')
fields = cursor.fetchall()

# Print the table fields
for field in fields:
    print(field)

# Close the connection
conn.close()

(0, 'id', 'INTEGER', 0, None, 1)
(1, 'name', 'TEXT', 1, None, 0)
(2, 'age', 'INTEGER', 0, None, 0)
(3, 'email', 'TEXT', 0, None, 0)


In [76]:
# Connect to the existing database
conn = sqlite3.connect('new_database.db')

# Create a cursor object
cursor = conn.cursor()

# Fetch all records from the users table
cursor.execute('SELECT * FROM users')
registers = cursor.fetchall()

# Print the fetched records
for register in registers:
    print(register)

# Close the connection
conn.close()

(2, 'Alice', 28, 'alice@example.com')
(3, 'Bob', 34, 'bob@example.com')
(4, 'Charlie', 22, 'charlie@example.com')
(5, 'Alice', 28, 'alice@example.com')
(6, 'Bob', 34, 'bob@example.com')
(7, 'Charlie', 22, 'charlie@example.com')


In [77]:
# Connect to the existing database
conn = sqlite3.connect('new_database.db')

# Create a cursor object
cursor = conn.cursor()

# Fetch all records from the users table
cursor.execute('SELECT * FROM users')
registers = cursor.fetchall()

# Print the fetched records
for register in registers:
    print(register)

# Close the connection
conn.close()

(2, 'Alice', 28, 'alice@example.com')
(3, 'Bob', 34, 'bob@example.com')
(4, 'Charlie', 22, 'charlie@example.com')
(5, 'Alice', 28, 'alice@example.com')
(6, 'Bob', 34, 'bob@example.com')
(7, 'Charlie', 22, 'charlie@example.com')


In [78]:
import pandas as pd

# Create a DataFrame from the registers
df_registers = pd.DataFrame(registers, columns=['id', 'name', 'age', 'email'])

# Display the DataFrame
df_registers

id     name  age                email
0   2    Alice   28    alice@example.com
1   3      Bob   34      bob@example.com
2   4  Charlie   22  charlie@example.com
3   5    Alice   28    alice@example.com
4   6      Bob   34      bob@example.com
5   7  Charlie   22  charlie@example.com

In [79]:

#connect to a database
conn = sqlite3.connect('new_database.db')

#create a cursor object
cursor = conn.cursor()

#fetch all records from the users table
cursor.execute('SELECT * FROM users')
registers = cursor.fetchall()

for register in registers:
    print(register)



(2, 'Alice', 28, 'alice@example.com')
(3, 'Bob', 34, 'bob@example.com')
(4, 'Charlie', 22, 'charlie@example.com')
(5, 'Alice', 28, 'alice@example.com')
(6, 'Bob', 34, 'bob@example.com')
(7, 'Charlie', 22, 'charlie@example.com')


In [80]:
#close the connection
conn.close()

In [81]:
obj = pd.Series([4, 7, -5, 3])

In [82]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [83]:
obj.array

<NumpyExtensionArray>
[np.int64(4), np.int64(7), np.int64(-5), np.int64(3)]
Length: 4, dtype: int64

In [84]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [85]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [86]:
import pandas as pd

In [87]:
obj = pd.Series([4, 7, -5, 3])

In [88]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [89]:
obj.array

<NumpyExtensionArray>
[np.int64(4), np.int64(7), np.int64(-5), np.int64(3)]
Length: 4, dtype: int64

In [90]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [91]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
"year": [2000, 2001, 2002, 2001, 2002, 2003],
"pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [92]:
data

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [93]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2