In [1]:
a, b = 0, 1
while b < 2000000:
    print(b, end=' ')
    a, b = b, a+b

1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765 10946 17711 28657 46368 75025 121393 196418 317811 514229 832040 1346269 

In [1]:
a, b = 0, 1
while b < 20000000:
    print(b, end=' ')
    a, b = b, a+b


1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765 10946 17711 28657 46368 75025 121393 196418 317811 514229 832040 1346269 2178309 3524578 5702887 9227465 14930352 

In [1]:
2+2


4

In [2]:
import numpy as np

array = np.array(range(10))


In [3]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
array1 = np.array(range(100))

In [5]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [6]:
array1 * 2

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [2]:
import numpy as np
random_numbers = np.random.rand(10)
print(random_numbers)

[0.21209613 0.60300974 0.34424594 0.63516576 0.97907595 0.80837456
 0.70206546 0.66545974 0.00930185 0.29252311]


In [3]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [4]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [5]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [6]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [7]:
data1 = [6, 7.5, 8, 0, 1]

In [8]:
arr1 = np.array(data1)

In [9]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [11]:
arr2 = np.array(data2)

In [12]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr2.shape

(2, 4)

In [14]:
arr1.dtype

dtype('float64')

In [15]:
arr2.dtype

dtype('int64')

In [16]:
arr3 = np.arange(10)

In [17]:
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr2.dtype

dtype('int64')

In [19]:
floatarr2 = arr2.astype(np.float64)

In [20]:
floatarr2.dtype

dtype('float64')

In [21]:
floatarr2

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [2]:
arr = np.arange(10)

In [3]:
arr_slc = arr[5:8]

In [4]:
arr_slc

array([5, 6, 7])

In [5]:
arr_slc[0:2] = 12

In [6]:
arr_slc

array([12, 12,  7])

In [7]:
arr_slc[0:] = 12

In [8]:
arr_slc

array([12, 12, 12])

In [9]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [10]:
arr_slc[1] = 12345

In [11]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [12]:
arr_slc[:] = 64

In [13]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [1]:
import numpy as np

In [14]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [36]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [37]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr2d[2]

array([7, 8, 9])

In [39]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [41]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [42]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [43]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4 ]])

In [44]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [45]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [46]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])